# syntax=docker.io/docker/dockerfile:1

FROM node:lts-alpine AS base
RUN corepack enable

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

RUN mkdir /code
WORKDIR /code

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock .yarnrc.yml ./
RUN corepack prepare --activate
RUN yarn install --immutable

# Dev runner image, copy all the installed modules run next
# No need to copy code as we mount it as a volume for hot reloading
FROM base AS runner
RUN mkdir /code
WORKDIR /code
COPY --from=deps /code/node_modules ./node_modules
CMD ["yarn" ,"dev", "-p", "3000"]