services:
  frontend:
    container_name: mui-tailwind-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/code
      - /code/.next
  reverse-proxy:
    depends_on:
      - frontend
    image: caddy:latest
    ports:
      - 3031:3031
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
